# Generated by Django 2.1.5 on 2019-01-08 06:57

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xgame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dateJoined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iStuff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iSuperUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastLogin',
        ),
        migrations.AddField(
            model_name='user',
            name='console',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
